import type { Metadata } from "next";
import {
  DEFAULT_LOCALE,
  getLocaleOpenGraphLanguage,
  getLocaleSchemaLanguage,
  getTranslation,
  SUPPORTED_LOCALES,
  type Locale,
} from "@/lib/i18n";
import { getToolTranslation } from "@/lib/tool-i18n";

export const siteConfig = {
  name: "IP Info",
  shortName: "IP Info",
  description:
    "Free network tools for public IP addresses, ASN, DNS, WHOIS, CDN detection, reachability and IP reputation.",
  url: "https://ip-info.leunos.com",
  locale: "en_US",
  keywords: [
    "public IP",
    "my IP",
    "IP lookup",
    "ASN lookup",
    "DNS lookup",
    "WHOIS",
    "CDN check",
    "PeeringDB",
    "ping test",
    "network analysis",
    "IP reputation",
    "blacklist check",
  ],
};

// 1200×630 PNG generated by scripts/generate-icons.mjs. Social networks do
// not render SVG og:images, so the preview card has to be a raster asset.
export const defaultOpenGraphImage = "/og-image.png";
const openGraphImageWidth = 1200;
const openGraphImageHeight = 630;

/** Sentence-closing marks that already appear at the end of a subtitle. */
const SENTENCE_MARKS = /[.!?…。！？।]/;

/** The terminator that reads naturally in the locale's own script. */
function sentenceMark(locale: Locale): string {
  if (locale === "ja" || locale === "zh-CN" || locale === "zh-TW") return "。";
  if (locale === "hi") return "।";
  return ".";
}

export function getSiteDescription(locale: Locale): string {
  const t = getTranslation(locale);
  const toolT = getToolTranslation(locale);
  const home = t.homeSubtitle.trim();
  // CJK and Hindi subtitles already end with their own sentence mark; only
  // add one where the catalog has none, so no locale ends up with "。.".
  const lead = SENTENCE_MARKS.test(home) ? home : `${home}${sentenceMark(locale)}`;
  return `${lead} ${toolT.dnsSubtitle} ${toolT.pingSubtitle} ${toolT.reputationSubtitle}`;
}

export function getSiteKeywords(locale: Locale): string[] {
  const t = getTranslation(locale);
  const toolT = getToolTranslation(locale);
  return [
    t.homeTitle,
    t.checkTitle,
    toolT.asnTitle,
    toolT.dnsTitle,
    toolT.whoisTitle,
    toolT.cdnTitle,
    toolT.pingTitle,
    toolT.reputationTitle,
    "ASN",
    "BGP",
    "DNS",
    "WHOIS",
    "CDN",
    "IPv4",
    "IPv6",
    "PeeringDB",
  ];
}

function getOpenGraphImageAlt(locale: Locale): string {
  return `${siteConfig.name} – ${getToolTranslation(locale).brandTagline}`;
}

/** Schema.org `inLanguage` tags for every UI locale, using the central registry. */
export const schemaInLanguage = SUPPORTED_LOCALES.map((locale) =>
  getLocaleSchemaLanguage(locale),
);

/**
 * Absolute document title. Next.js `title.template` is not applied to
 * `app/page.tsx`. A title that already *is* the site name (e.g. the English
 * or German home page) is not suffixed, which would read "IP Info | IP Info".
 */
export function documentTitle(title: string): string {
  return title === siteConfig.name ? title : `${title} | ${siteConfig.name}`;
}

/**
 * Canonical URL without a trailing slash on the site root, so `<link rel="canonical">`,
 * the sitemap, and JSON-LD `@id`/`url` values all agree.
 */
export function canonicalUrl(path = "/"): string {
  const url = new URL(path || "/", siteConfig.url);
  if (url.pathname === "/") {
    return `${siteConfig.url}${url.search}${url.hash}`;
  }
  const pathname = url.pathname.replace(/\/+$/, "");
  return `${url.origin}${pathname}${url.search}${url.hash}`;
}

export function createPageMetadata({
  title,
  description,
  path = "/",
  keywords = [],
  locale = DEFAULT_LOCALE,
}: {
  title: string;
  description: string;
  path?: string;
  keywords?: string[];
  locale?: Locale;
}): Metadata {
  const canonical = canonicalUrl(path);

  return {
    title: {
      absolute: documentTitle(title),
    },
    description,
    keywords: [...getSiteKeywords(locale), ...keywords],
    applicationName: siteConfig.name,
    authors: [{ name: siteConfig.name, url: siteConfig.url }],
    creator: siteConfig.name,
    publisher: siteConfig.name,
    category: "technology",
    formatDetection: {
      telephone: false,
      email: false,
      address: false,
    },
    alternates: {
      // The app intentionally has one canonical URL per route. Locale is
      // negotiated from Accept-Language and an explicit functional cookie;
      // emitting hreflang URLs for non-existent locale paths would be false.
      canonical,
      types: {
        "text/plain": `${siteConfig.url}/llms.txt`,
      },
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-image-preview": "large",
        "max-snippet": -1,
        "max-video-preview": -1,
      },
    },
    openGraph: {
      type: "website",
      locale: getLocaleOpenGraphLanguage(locale),
      url: canonical,
      title,
      description,
      siteName: siteConfig.name,
      images: [
        {
          url: defaultOpenGraphImage,
          width: openGraphImageWidth,
          height: openGraphImageHeight,
          alt: getOpenGraphImageAlt(locale),
          type: "image/png",
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [
        {
          url: defaultOpenGraphImage,
          width: openGraphImageWidth,
          height: openGraphImageHeight,
          alt: getOpenGraphImageAlt(locale),
          type: "image/png",
        },
      ],
    },
  };
}
