import type { Metadata } from "next";

export const siteConfig = {
  name: "IP Auskunft",
  shortName: "IP Auskunft",
  description:
    "Kostenlose Netzwerk-Tools für öffentliche IP-Adressen, ASN, DNS, Whois, CDN-Erkennung, Erreichbarkeit und IP-Reputation.",
  url: "https://ip-info.leunos.com",
  locale: "de_DE",
  keywords: [
    "IP Adresse",
    "Meine IP",
    "IP Lookup",
    "ASN Lookup",
    "DNS Lookup",
    "Whois",
    "CDN Check",
    "PeeringDB",
    "Ping Test",
    "Netzwerk Analyse",
    "IP Reputation",
    "Blacklist Check",
  ],
};

// 1200×630 PNG generated by scripts/generate-icons.mjs. Social networks do
// not render SVG og:images, so the preview card has to be a raster asset.
export const defaultOpenGraphImage = "/og-image.png";
const openGraphImageWidth = 1200;
const openGraphImageHeight = 630;

export function createPageMetadata({
  title,
  description,
  path = "/",
  keywords = [],
}: {
  title: string;
  description: string;
  path?: string;
  keywords?: string[];
}): Metadata {
  const canonical = new URL(path, siteConfig.url).toString();

  return {
    title,
    description,
    keywords: [...siteConfig.keywords, ...keywords],
    applicationName: siteConfig.name,
    authors: [{ name: siteConfig.name, url: siteConfig.url }],
    creator: siteConfig.name,
    publisher: siteConfig.name,
    category: "technology",
    formatDetection: {
      telephone: false,
      email: false,
      address: false,
    },
    alternates: {
      canonical,
      types: {
        "text/plain": `${siteConfig.url}/llms.txt`,
      },
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-image-preview": "large",
        "max-snippet": -1,
        "max-video-preview": -1,
      },
    },
    openGraph: {
      type: "website",
      locale: siteConfig.locale,
      url: canonical,
      title,
      description,
      siteName: siteConfig.name,
      images: [
        {
          url: defaultOpenGraphImage,
          width: openGraphImageWidth,
          height: openGraphImageHeight,
          alt: `${siteConfig.name} – Netzwerk- & IP-Toolkit`,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [defaultOpenGraphImage],
    },
  };
}
